### ISSUE TITLE
Check bài

### ISSUE THREAD

**Issue by HaiYenPham** [KhuongDuy-1110/KhuongDuy-1110.github.io#1]
https://github.com/KhuongDuy-1110/KhuongDuy-1110.github.io/blob/bb7886bb4e7a16727deb4c323c95f57117af713f/index.html#L96

Toàn girl xinh thế này không thích sao được ✌️ 
Bài này của em ổn rồi nha, phần này khá quan trọng hầu như làm gì cũng có nên học kỹ nhé!
<3 Thân ái và Quyết thắng <3

**Comment by KhuongDuy-1110** [comment]
vâng ạ :D
