### ISSUE TITLE
check bài 2

### ISSUE THREAD

**Issue by HaiYenPham** [KhuongDuy-1110/KhuongDuy-1110.github.io#2]
https://github.com/KhuongDuy-1110/KhuongDuy-1110.github.io/blob/fa9a47d4795e959f4c7ac189efc63fa01feda126/index.html#L11

bài này cũng ok rùi nè! cố gắng phát huy nhé! 
<3

**Comment by KhuongDuy-1110** [comment]
vaang aj :33
